version: "3.8"
services:
  order_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    depends_on:
      - order_db
    volumes:
      - .:/app
    networks:
      - lahmi

  order_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33068:3306
    networks:
      - lahmi

networks:
 lahmi:
  external: true